### ISSUE TITLE
Dockerfile fix

### ISSUE THREAD

**Issue by anusharanganathan** [antleaf/nims-hyrax#60]
[Dockerfile](https://github.com/antleaf/nims-hyrax/blob/develop/hyrax/Dockerfile#L38-L42) is failing with jessie backports.

Fix it by installing openjdk instead
```
    openjdk-8-jre-headless
    # # install open-jdk and ca-certs from jessie-backports
    # && apt-get install -t jessie-backports -y --no-install-recommends openjdk-8-jre-headless ca-certificates-java \
    # && apt-get clean \
    # && rm -rf /var/lib/apt/lists/* \
# && /var/lib/dpkg/info/ca-certificates-java.postinst configure
```
java is needed by fits and likely by libreoffice

**Comment by Steven-Eardley** [comment]
Is there any reason we can't install a more current JRE? I believe at least LibreOffice isn't fussy about which version is installed.

**Comment by anusharanganathan** [comment]
FITS probably depends on Java 7 or 8. We are using an older version of FITS. See https://github.com/samvera/hyrax#prerequisites and https://github.com/harvard-lts/fits/issues/140
