### ISSUE TITLE
Cannot update nested attributes

### ISSUE THREAD

**Issue by anusharanganathan** [antleaf/nims-hyrax#69]
* The nested attributes aren't being updated
* It is possible to create new nested attributes and delete existing attributes, but not possible to edit.
* This is true with form and model

**Comment by anusharanganathan** [comment]
I have added tests to the model to test  create another, delete and update. The update tests do fail

**Comment by geekscruff** [comment]
Some screenshots to illustrate the issue:

<img width="841" alt="Screenshot 2019-09-09 at 10 26 24" src="https://user-images.githubusercontent.com/722117/64524840-5c5f1100-d2f7-11e9-8b46-f79a020cd951.png">

<img width="1038" alt="Screenshot 2019-09-09 at 10 25 13" src="https://user-images.githubusercontent.com/722117/64524837-59642080-d2f7-11e9-90bc-4b57c5cf7dd2.png">

**Comment by geekscruff** [comment]
Fixed by #109
